# Generated by Django 5.0 on 2023-12-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
